### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by samhithasanka** [limbo018/DREAMPlace#135]
**python3 dreamplace/Placer.py test/ispd2005/adaptec1.json**
While executing the above command in Install directory, I'm getting the below error.
Traceback (most recent call last):
  File "/home/a0393510local/DREAMPlace_CT/build/DREAMPlace/dreamplace/Placer.py", line 21, in <module>
    import PlaceDB
  File "/home/a0393510local/DREAMPlace_CT/build/DREAMPlace/dreamplace/PlaceDB.py", line 18, in <module>
    import dreamplace.ops.place_io.place_io as place_io
  File "/home/a0393510local/DREAMPlace_CT/build/DREAMPlace/dreamplace/ops/place_io/place_io.py", line 9, in <module>
    import dreamplace.ops.place_io.place_io_cpp as place_io_cpp
ModuleNotFoundError: No module named 'dreamplace.ops.place_io.place_io_cpp'
So, I've tried building cmake in place_io directory 
But, then I'm getting the following error.
**cmake ..**
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:36 (add_pytorch_extension):
  Unknown CMake command "add_pytorch_extension".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

Could anyone tell what I'm doing wrong.

**Comment by limbo018** [comment]
It looks like you mixed up **source code directory**, **build directory**, and **install directory**.
When you clone or download the code to a folder, say ```DREAMPlace/```, that's source code directory. Under the source code directory, you have files like README.md, CMakeLists.txt, etc. 
If you follow the default instructions to compile the code, you will have ```DREAMPlace/build``` as your build directory. 
If you follow the default instructions to install the code (after running ```make install```), you will have ```DREAMPlace/install``` as your install directory. 

You need to run from the **install directory**. That is, ```cd DREAMPlace/install``` before running the program.
