### ISSUE TITLE
I meet error

### ISSUE THREAD

**Issue by Lulinhao** [limbo018/DREAMPlace#139]
I get this error when I run the program, but I have it compiled.

- Traceback (most recent call last):
  File "/home/wjz/djh/DREAMPlace/install/dreamplace/Placer.py", line 22, in <module>
    import Timer
  File "/home/wjz/djh/DREAMPlace/install/dreamplace/Timer.py", line 10, in <module>
    import dreamplace.ops.timing.timing as timing
  File "/home/wjz/djh/DREAMPlace/install/dreamplace/ops/timing/timing.py", line 5, in <module>
    import dreamplace.ops.timing.timing_cpp as timing_cpp
ImportError: /home/wjz/.conda/envs/new/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/wjz/djh/DREAMPlace/install/dreamplace/ops/timing/timing_cpp.cpython-310-x86_64-linux-gnu.so)

**Comment by limbo018** [comment]
Hi, GLIBCXX problem usually comes from your system configuration. Have you tried the following solution?

https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

Besides, it looks like you are using higher gcc version than recommended gcc 7.

**Comment by Lulinhao** [comment]
thx
