### ISSUE TITLE
While running DREAMPlace following error occured. Please help if any body knows it 

### ISSUE THREAD

**Issue by bnbray** [limbo018/DREAMPlace#58]
bnb@BNB-HP:~/DREAMPlace$ python dreamplace/Placer.py test/ispd2005/adaptec1.json
Traceback (most recent call last):
  File "dreamplace/Placer.py", line 21, in <module>
    import PlaceDB
  File "/home/bnb/DREAMPlace/dreamplace/PlaceDB.py", line 16, in <module>
    import dreamplace.ops.place_io.place_io as place_io 
  File "/home/bnb/DREAMPlace/dreamplace/ops/place_io/place_io.py", line 9, in <module>
    import dreamplace.ops.place_io.place_io_cpp as place_io_cpp
ImportError: /home/bnb/DREAMPlace/dreamplace/ops/place_io/place_io_cpp.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

**Comment by liumengbjut** [comment]
It seems you did not run the code in you installed folder.

**Comment by bnbray** [comment]
Thanks for the reply
