### ISSUE TITLE
dreamplace.ops.rmst_wl.rmst_wl_cpp not found

### ISSUE THREAD

**Issue by LawrenceXia2008** [limbo018/DREAMPlace#66]
python unittest/ops/rmst_wl_unittest.py 
Traceback (most recent call last):
  File "unittest/ops/rmst_wl_unittest.py", line 18, in <module>
    from dreamplace.ops.rmst_wl import rmst_wl
  File "DREAMPlace/dreamplace/ops/rmst_wl/rmst_wl.py", line 11, in <module>
    import dreamplace.ops.rmst_wl.rmst_wl_cpp as rmst_wl_cpp
ModuleNotFoundError: No module named 'dreamplace.ops.rmst_wl.rmst_wl_cpp'

**Comment by limbo018** [comment]
Hi, I commented the rmst_wl op in ops/CMakeLists.txt, as this operator is not used in the default flow. You can uncomment it.

**Comment by LawrenceXia2008** [comment]
it is fixed. thank you!
