### ISSUE TITLE
DEF file reading failed

### ISSUE THREAD

**Issue by dearmrlv** [limbo018/DREAMPlace#81]
Hi, Professor Lin. This is an awesome project. And I encountered some problem when using it. 
I tried to use DREAMPlace to perform global placement for my project, but error appeared, and the log is showed below:
```
[INFO   ] lef_input = test/tcbn45gsbwp_9lm7X1ZRDL.lef
[INFO   ] def_input = test_def/fp.def
[INFO   ] verilog_input = ICC_results/APCA_0.25r_0.45u/top-compiled.v
[INFO   ] bookshelf_aux_input =
[INFO   ] bookshelf_pl_input =
[INFO   ] def_size_input =
[INFO   ] def_output = fp-out.def
[INFO   ] rpt_output =
[INFO   ] target_util = 0
[INFO   ] max_displace = 0
[INFO   ] bin size = (10, 10) #rows
[INFO   ] sbin size = (5, 5) #rows
[INFO   ] bin_space_threshold = 0.2
[INFO   ] abu = 2,10 5,5 10,2 20,1
[INFO   ] def_ignore_cells =
[INFO   ] macro_obs_aware_layers =
[INFO   ] enable_place = true
[INFO   ] enable_legalize = true
[INFO   ] evaluate_overlap = false
[INFO   ] move_multi_row_cell = true
[INFO   ] align_power_line = true
[INFO   ] cluster_cell = false
[INFO   ] sort_nets_by_degree = false
[INFO   ] file_format = DEF
[INFO   ] max_iters = 6
[INFO   ] reading test/tcbn45gsbwp_9lm7X1ZRDL.lef
[INFO   ] set CORE site to core, 280 x 2520
[INFO   ] set CORE site to bcore, 280 x 5040
[INFO   ] set CORE site to bcoreExt, 280 x 5040
[INFO   ] set CORE site to ccore, 280 x 7560
[INFO   ] set CORE site to dcore, 280 x 10080
[INFO   ] set CORE site to gacore, 1400 x 2520
[INFO   ] set CORE site to gabcore, 1400 x 5040
[INFO   ] reading test_def/fp.def
[INFO   ] detect 149 rows, 51809 components, 4354 IO pins, 56099 nets, 0 blockages
TECHNOLOGY TSMC_N40_9lm7X1ZRDL_TCBN40 ;
Traceback (most recent call last):
  File "run_DREAMPlace.py", line 5, in <module>
    db, params = read_db(sys.argv[1])
  File "/lustre/S/lvzhengyang/CA/read_db.py", line 37, in read_db
    placedb(params)
  File "/workspace/S/lvzhengyang/DREAMPlace_Py38_2/dreamplace/PlaceDB.py", line 552, in __call__
    self.read(params)
  File "/workspace/S/lvzhengyang/DREAMPlace_Py38_2/dreamplace/PlaceDB.py", line 435, in read
    self.rawdb = place_io.PlaceIOFunction.read(params)
  File "/workspace/S/lvzhengyang/DREAMPlace_Py38_2/dreamplace/ops/place_io/place_io.py", line 35, in read
    return place_io_cpp.forward(args.split(' '))
IndexError: _Map_base::at
```
And here is my config, LEF and DEF file:
The DEF file is generated by ICC 2018.
[lefdef.zip](https://github.com/limbo018/DREAMPlace/files/9228586/lefdef.zip)

Thanks so much to have a look at my issue, and I'll be greatly appreciated for your suggestions!

**Comment by limbo018** [comment]
Hi, I found one problem is that the ROW definition in DEF. The row macro name "unit" is inconsistent with the site names in LEF. You need to replace it to "core".

**Comment by dearmrlv** [comment]
Thank you Professor! Your suggestion worked, and solved the above-mentioned error. However, I met another error and the log is below. Could you provide some suggestions on it?
```
[INFO   ] lef_input = test/tcbn45gsbwp_9lm7X1ZRDL.lef
[INFO   ] def_input = test_def/fp.def
[INFO   ] verilog_input = ICC_results/APCA_1.0r_0.55u/top-compiled.v
[INFO   ] bookshelf_aux_input =
[INFO   ] bookshelf_pl_input =
[INFO   ] def_size_input =
[INFO   ] def_output = fp-out.def
[INFO   ] rpt_output =
[INFO   ] target_util = 0
[INFO   ] max_displace = 0
[INFO   ] bin size = (10, 10) #rows
[INFO   ] sbin size = (5, 5) #rows
[INFO   ] bin_space_threshold = 0.2
[INFO   ] abu = 2,10 5,5 10,2 20,1
[INFO   ] def_ignore_cells =
[INFO   ] macro_obs_aware_layers =
[INFO   ] enable_place = true
[INFO   ] enable_legalize = true
[INFO   ] evaluate_overlap = false
[INFO   ] move_multi_row_cell = true
[INFO   ] align_power_line = true
[INFO   ] cluster_cell = false
[INFO   ] sort_nets_by_degree = false
[INFO   ] file_format = DEF
[INFO   ] max_iters = 6
[INFO   ] reading test/tcbn45gsbwp_9lm7X1ZRDL.lef
[INFO   ] set CORE site to core, 280 x 2520
[INFO   ] set CORE site to bcore, 280 x 5040
[INFO   ] set CORE site to bcoreExt, 280 x 5040
[INFO   ] set CORE site to ccore, 280 x 7560
[INFO   ] set CORE site to dcore, 280 x 10080
[INFO   ] set CORE site to gacore, 1400 x 2520
[INFO   ] set CORE site to gabcore, 1400 x 5040
[INFO   ] reading test_def/fp.def
[INFO   ] detect 269 rows, 51809 components, 4354 IO pins, 56099 nets, 0 blockages
TECHNOLOGY TSMC_N40_9lm7X1ZRDL_TCBN40 ;
[WARNING] no Bookshelf file specified
[WARNING] no additional Bookshelf .pl file specified
[WARNING] 0 nets with 0 pins from same nodes
[WARNING] 0 nets should be ignored due to not enough pins
[INFO   ] sort nodes in the order of movable and fixed
[INFO   ] Group cells for fence regions
[INFO   ] Construct 0 groups
[INFO   ] Fence region groups done
[DEBUG  ] num_terminals 0, numFixed 0, numPlaceBlockages 0, num_terminal_NIs 4354
[DEBUG  ] fixed area overlap: 0 fixed area total: 0, space area = 4.6066e+11
/workspace/S/lvzhengyang/DREAMPlace_Py38_2/dreamplace/PlaceDB.py:538: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.node2pin_map = np.array(self.node2pin_map)
/workspace/S/lvzhengyang/DREAMPlace_Py38_2/dreamplace/PlaceDB.py:543: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.net2pin_map = np.array(self.net2pin_map)
WARNING:root:net weights are all the same, ignored
WARNING:root:quadratic density penalty is disabled, density weight update is forced to be based on HPWL
[INFO   ] Macro legalization: regard 0 cells as dummy fixed (movable macros)
[INFO   ] Macro legalization takes 0.100158 ms
[DEBUG  ] Standard cell legalization blank_num_bins_y = 134
[DEBUG  ] Standard cell legalization iteration 0 with 1x1 bins
[DEBUG  ] Standard cell legalization #bin_blanks
[DEBUG  ] #bin_objs = 134
[DEBUG  ] 2. move node 9688 from 325.429 to 321.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 6208 from 325.429 to 321.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 17215 from 326.429 to 325.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 47004 from 325.429 to 324.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 47001 from 324.429 to 323.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 5698 from 324.429 to 320.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 44100 from 324.429 to 323.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 17277 from 324.429 to 323.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 31468 from 326.429 to 324.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 44559 from 325.429 to 323.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 9634 from 321.429 to 317.429, blank (71.4286, 321.429)
[DEBUG  ] 2. move node 17278 from 323.429 to 322.429, blank (71.4286, 323.429)
[DEBUG  ] 2. move node 2303 from 326.429 to 324.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 3121 from 326.429 to 324.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 31623 from 324.429 to 322.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 44627 from 325.429 to 324.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 1888 from 325.429 to 323.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 17250 from 322.429 to 321.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 47148 from 321.429 to 320.429, blank (71.4286, 321.429)
[DEBUG  ] 2. move node 31542 from 324.429 to 323.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 17258 from 320.429 to 319.429, blank (71.4286, 320.429)
[DEBUG  ] 2. move node 31544 from 326.429 to 325.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 2018 from 324.429 to 322.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 31841 from 326.429 to 325.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 31444 from 323.429 to 321.429, blank (71.4286, 323.429)
[DEBUG  ] 2. move node 31702 from 324.429 to 322.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 31599 from 322.429 to 320.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 6012 from 320.429 to 316.429, blank (71.4286, 320.429)
[DEBUG  ] 2. move node 31465 from 323.429 to 322.429, blank (71.4286, 323.429)
[DEBUG  ] 2. move node 31602 from 319.429 to 317.429, blank (71.4286, 319.429)
[DEBUG  ] 2. move node 49581 from 323.429 to 322.429, blank (71.4286, 323.429)
[DEBUG  ] 2. move node 8990 from 325.429 to 321.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 47118 from 323.429 to 322.429, blank (71.4286, 323.429)
[DEBUG  ] 2. move node 31717 from 321.429 to 319.429, blank (71.4286, 321.429)
[DEBUG  ] 2. move node 47034 from 322.429 to 321.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 9687 from 320.429 to 316.429, blank (71.4286, 320.429)
[DEBUG  ] 2. move node 31596 from 321.429 to 320.429, blank (71.4286, 321.429)
[DEBUG  ] 2. move node 31709 from 321.429 to 319.429, blank (71.4286, 321.429)
[DEBUG  ] 2. move node 31622 from 322.429 to 321.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 2304 from 320.429 to 318.429, blank (71.4286, 320.429)
[DEBUG  ] 2. move node 10489 from 316.429 to 312.429, blank (71.4286, 316.429)
[DEBUG  ] 2. move node 31607 from 319.429 to 317.429, blank (71.4286, 319.429)
[DEBUG  ] 2. move node 47036 from 319.429 to 318.429, blank (71.4286, 319.429)
[DEBUG  ] 2. move node 10656 from 318.429 to 314.429, blank (71.4286, 318.429)
[DEBUG  ] 2. move node 49255 from 325.429 to 324.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 31707 from 324.429 to 323.429, blank (71.4286, 324.429)
[DEBUG  ] 2. move node 2052 from 322.429 to 320.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 31796 from 326.429 to 325.429, blank (71.4286, 326.429)
[DEBUG  ] 2. move node 2306 from 318.429 to 316.429, blank (71.4286, 318.429)
[DEBUG  ] 2. move node 31705 from 322.429 to 320.429, blank (71.4286, 322.429)
[DEBUG  ] 2. move node 12055 from 313.429 to 308.429, blank (71.4286, 313.429)
[DEBUG  ] 2. move node 31797 from 325.429 to 324.429, blank (71.4286, 325.429)
[DEBUG  ] 2. move node 3120 from 320.429 to 318.429, blank (71.4286, 320.429)
... (more similar logs)
[ERROR  ] row 133 (550.229, 553.829), overlap node 17185 (483.429, 550.229, 484.029, 552.029) with node 47433 (483.429, 550.229, 484.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 17768 (484.429, 550.229, 485.029, 552.029) with node 46928 (484.429, 550.229, 485.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 10421 (485.429, 550.229, 489.429, 552.029) with node 14672 (485.429, 550.229, 486.029, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 7892 (487.429, 550.229, 491.429, 552.029) with node 47297 (489.429, 550.229, 490.229, 552.029), gap 2
[ERROR  ] row 133 (550.229, 553.829), overlap node 17603 (491.429, 550.229, 492.029, 552.029) with node 46931 (491.429, 550.229, 492.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 17179 (492.429, 550.229, 493.029, 552.029) with node 47296 (492.429, 550.229, 493.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 45790 (493.429, 550.229, 494.229, 552.029) with node 46930 (493.429, 550.229, 494.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 17147 (494.429, 550.229, 495.029, 552.029) with node 17708 (494.429, 550.229, 495.029, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 43738 (495.429, 550.229, 496.029, 552.029) with node 45791 (495.429, 550.229, 496.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 7948 (496.429, 550.229, 500.429, 552.029) with node 10254 (496.429, 550.229, 500.429, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 46948 (500.429, 550.229, 501.229, 552.029) with node 47425 (500.429, 550.229, 501.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 17155 (501.429, 550.229, 502.029, 552.029) with node 45770 (501.429, 550.229, 502.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 14693 (502.429, 550.229, 503.029, 552.029) with node 46950 (502.429, 550.229, 503.229, 552.029), gap 0.600006
[ERROR  ] row 133 (550.229, 553.829), overlap node 8394 (503.429, 550.229, 507.429, 552.029) with node 47307 (503.429, 550.229, 504.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 8393 (507.429, 550.229, 511.429, 552.029) with node 17636 (507.429, 550.229, 508.029, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 45993 (511.429, 550.229, 512.229, 552.029) with node 47182 (511.429, 550.229, 512.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 46934 (512.429, 550.229, 513.229, 552.029) with node 47318 (512.429, 550.229, 513.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 17137 (513.429, 550.229, 514.029, 552.029) with node 17827 (513.429, 550.229, 514.029, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 17151 (514.429, 550.229, 515.029, 552.029) with node 47212 (514.429, 550.229, 515.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 17619 (515.429, 550.229, 516.029, 552.029) with node 46933 (515.429, 550.229, 516.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 10487 (516.429, 550.229, 520.429, 552.029) with node 17149 (516.429, 550.229, 517.029, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 10222 (519.429, 550.229, 523.429, 552.029) with node 47232 (520.429, 550.229, 521.229, 552.029), gap 3
[ERROR  ] row 133 (550.229, 553.829), overlap node 10446 (521.429, 550.229, 525.429, 552.029) with node 14865 (523.429, 550.229, 524.029, 552.029), gap 2
[ERROR  ] row 133 (550.229, 553.829), overlap node 17939 (525.429, 550.229, 526.029, 552.029) with node 47061 (525.429, 550.229, 526.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 9719 (526.429, 550.229, 530.429, 552.029) with node 46951 (526.429, 550.229, 527.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 10216 (530.429, 550.229, 534.429, 552.029) with node 45981 (530.429, 550.229, 531.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 14868 (534.429, 550.229, 535.029, 552.029) with node 47173 (534.429, 550.229, 535.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 14670 (535.429, 550.229, 536.029, 552.029) with node 47210 (535.429, 550.229, 536.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 14682 (536.429, 550.229, 537.029, 552.029) with node 47242 (536.429, 550.229, 537.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 17132 (537.429, 550.229, 538.029, 552.029) with node 43829 (537.429, 550.229, 538.029, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 17830 (538.429, 550.229, 539.029, 552.029) with node 45793 (538.429, 550.229, 539.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 45787 (539.429, 550.229, 540.229, 552.029) with node 47076 (539.429, 550.229, 540.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 17774 (540.429, 550.229, 541.029, 552.029) with node 46955 (540.429, 550.229, 541.229, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 45781 (541.429, 550.229, 542.229, 552.029) with node 47241 (541.429, 550.229, 542.229, 552.029), gap 0.799988
[ERROR  ] row 133 (550.229, 553.829), overlap node 10247 (542.429, 550.229, 546.429, 552.029) with node 45788 (542.429, 550.229, 543.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 14664 (546.429, 550.229, 547.029, 552.029) with node 17633 (546.429, 550.229, 547.029, 552.029), gap 0.599976
[ERROR  ] row 133 (550.229, 553.829), overlap node 10220 (547.429, 550.229, 551.429, 552.029) with node 45977 (547.429, 550.229, 548.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 8556 (551.429, 550.229, 555.429, 552.029) with node 44001 (551.429, 550.229, 552.229, 552.029), gap 4
[ERROR  ] row 133 (550.229, 553.829), overlap node 17130 (555.429, 550.229, 556.029, 552.029) with node 17909 (555.429, 550.229, 556.029, 552.029), gap 0.599976
[INFO   ] Legality check takes 1226.31 ms
```
Sorry to let you solve my puzzle again. I am appreciated for any of your suggestions!
Again, the lef and def is attached below.

[lefdef.zip](https://github.com/limbo018/DREAMPlace/files/9231560/lefdef.zip)

Best Wishes!

**Comment by limbo018** [comment]
This problem has been fixed with the latest commit. Could you pull and reinstall?

**Comment by dearmrlv** [comment]
Thank you so much! And my problem was finally solved. I'll close this issue .
